hello2: hello2.c
	clang hello2.c -o hello2
	
buggy: buggy.c
	clang buggy.c -o buggy -lcs50 -g

scores: scores.c
	clang scores.c -o scores -lcs50

hi: hi.c
	clang hi.c -o hi -lcs50

length: length.c
	clang length.c -o length -lcs50